In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("globalairquality.csv")

In [5]:
print(df)

                City       Country        Date   PM2.5    PM10    NO2    SO2  \
0            Bangkok      Thailand  2023-03-19   86.57   25.19  99.88  30.63
1           Istanbul        Turkey  2023-02-16   50.63   97.39  48.14   8.71
2     Rio de Janeiro        Brazil  2023-11-13  130.21   57.22  98.51   9.92
3             Mumbai         India  2023-03-16  119.70  130.52  10.96  33.03
4              Paris        France  2023-04-04   55.20   36.62  76.85  21.85
...              ...           ...         ...     ...     ...    ...    ...
9995    Johannesburg  South Africa  2023-09-16  147.85  184.34  90.33  34.93
9996          Berlin       Germany  2023-12-05   12.22  121.49  49.04   5.66
9997          Moscow        Russia  2023-11-26   44.07  143.62   8.41  32.58
9998          Berlin       Germany  2023-02-03   67.43   96.79  43.23  29.19
9999         Bangkok      Thailand  2023-06-13   16.34   28.80  50.48  21.20

        CO      O3  Temperature  Humidity  Wind Speed
0     4.46   36.29        17.67     59.35       13.76
1     3.40  144.16         3.46     67.51        6.36
2     0.12  179.31        25.29     29.30       12.87
3     7.74   38.65        23.15     99.97        7.71
4     2.00   67.09        16.02     90.28       14.16
...    ...     ...          ...       ...         ...
9995  2.81  191.45        -1.92     65.22       15.48
9996  2.10  184.56        -9.81     12.16       10.75
9997  0.69  167.68        39.35     53.95        4.56
9998  6.01  148.50        26.21     58.54        2.71
9999  0.49   17.41         2.50     66.05        5.01

[10000 rows x 12 columns]

In [6]:
df

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Bangkok,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Johannesburg,South Africa,2023-09-16,147.85,184.34,90.33,34.93,2.81,191.45,-1.92,65.22,15.48
9996,Berlin,Germany,2023-12-05,12.22,121.49,49.04,5.66,2.10,184.56,-9.81,12.16,10.75
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56
9998,Berlin,Germany,2023-02-03,67.43,96.79,43.23,29.19,6.01,148.50,26.21,58.54,2.71
9999,Bangkok,Thailand,2023-06-13,16.34,28.80,50.48,21.20,0.49,17.41,2.50,66.05,5.01

In [7]:
#selecting the data

In [8]:
df["Country"]

0           Thailand
1             Turkey
2             Brazil
3              India
4             France
            ...
9995    South Africa
9996         Germany
9997          Russia
9998         Germany
9999        Thailand
Name: Country, Length: 10000, dtype: object

In [9]:
df["City"]

0              Bangkok
1             Istanbul
2       Rio de Janeiro
3               Mumbai
4                Paris
             ...
9995      Johannesburg
9996            Berlin
9997            Moscow
9998            Berlin
9999           Bangkok
Name: City, Length: 10000, dtype: object

In [10]:
#selecting multiple columns

In [12]:
df[["Country","Temperature"]]

           Country  Temperature
0         Thailand        17.67
1           Turkey         3.46
2           Brazil        25.29
3            India        23.15
4           France        16.02
...            ...          ...
9995  South Africa        -1.92
9996       Germany        -9.81
9997        Russia        39.35
9998       Germany        26.21
9999      Thailand         2.50

[10000 rows x 2 columns]

In [13]:
df.loc[2]

City           Rio de Janeiro
Country                Brazil
Date               2023-11-13
PM2.5                  130.21
PM10                    57.22
NO2                     98.51
SO2                      9.92
CO                       0.12
O3                     179.31
Temperature             25.29
Humidity                 29.3
Wind Speed              12.87
Name: 2, dtype: object

In [14]:
df.iloc[2]

City           Rio de Janeiro
Country                Brazil
Date               2023-11-13
PM2.5                  130.21
PM10                    57.22
NO2                     98.51
SO2                      9.92
CO                       0.12
O3                     179.31
Temperature             25.29
Humidity                 29.3
Wind Speed              12.87
Name: 2, dtype: object

In [15]:
df.iloc[1:3]

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87

In [16]:
df.loc[1:3]

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71

In [17]:
#both rows and columns i.e, individual cell

In [20]:
df.loc[0:2,["Temperature","City"]]

   Temperature            City
0        17.67         Bangkok
1         3.46        Istanbul
2        25.29  Rio de Janeiro

In [21]:
df.columns

Index(['City', 'Country', 'Date', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3',
       'Temperature', 'Humidity', 'Wind Speed'],
      dtype='object')

In [23]:
df.iloc[0:2,1]

0    Thailand
1      Turkey
Name: Country, dtype: object

In [24]:
df.iloc[0:2,1:2]

    Country
0  Thailand
1    Turkey

In [25]:
#selecting single scalar value

In [26]:
df.at[0,"City"]

'Bangkok'

In [27]:
df.at[1,"City"]

'Istanbul'

In [28]:
df.columns

Index(['City', 'Country', 'Date', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3',
       'Temperature', 'Humidity', 'Wind Speed'],
      dtype='object')

In [29]:
df.iat[0,0]

'Bangkok'

In [31]:
df.iat[1,1]

'Turkey'

In [32]:
#copy and view

In [43]:
cities=df["City"].copy()

In [44]:
cities[0]="Vizag"

In [45]:
df["City"]

0                Vizag
1             Istanbul
2       Rio de Janeiro
3               Mumbai
4                Paris
             ...
9995      Johannesburg
9996            Berlin
9997            Moscow
9998            Berlin
9999           Bangkok
Name: City, Length: 10000, dtype: object

In [40]:
df["City"]

0                Vizag
1             Istanbul
2       Rio de Janeiro
3               Mumbai
4                Paris
             ...
9995      Johannesburg
9996            Berlin
9997            Moscow
9998            Berlin
9999           Bangkok
Name: City, Length: 10000, dtype: object

In [47]:
df

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Vizag,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Johannesburg,South Africa,2023-09-16,147.85,184.34,90.33,34.93,2.81,191.45,-1.92,65.22,15.48
9996,Berlin,Germany,2023-12-05,12.22,121.49,49.04,5.66,2.10,184.56,-9.81,12.16,10.75
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56
9998,Berlin,Germany,2023-02-03,67.43,96.79,43.23,29.19,6.01,148.50,26.21,58.54,2.71
9999,Bangkok,Thailand,2023-06-13,16.34,28.80,50.48,21.20,0.49,17.41,2.50,66.05,5.01

In [48]:
cities

0                Vizag
1             Istanbul
2       Rio de Janeiro
3               Mumbai
4                Paris
             ...
9995      Johannesburg
9996            Berlin
9997            Moscow
9998            Berlin
9999           Bangkok
Name: City, Length: 10000, dtype: object

In [50]:
df

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Vizag,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Johannesburg,South Africa,2023-09-16,147.85,184.34,90.33,34.93,2.81,191.45,-1.92,65.22,15.48
9996,Berlin,Germany,2023-12-05,12.22,121.49,49.04,5.66,2.10,184.56,-9.81,12.16,10.75
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56
9998,Berlin,Germany,2023-02-03,67.43,96.79,43.23,29.19,6.01,148.50,26.21,58.54,2.71
9999,Bangkok,Thailand,2023-06-13,16.34,28.80,50.48,21.20,0.49,17.41,2.50,66.05,5.01

In [52]:
citie=df["City"]

In [53]:
citie[0]="Bangkok"

C:\Users\Varas\AppData\Local\Temp\ipykernel_32416\2793584325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  citie[0]="Bangkok"

In [54]:
df

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Bangkok,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Johannesburg,South Africa,2023-09-16,147.85,184.34,90.33,34.93,2.81,191.45,-1.92,65.22,15.48
9996,Berlin,Germany,2023-12-05,12.22,121.49,49.04,5.66,2.10,184.56,-9.81,12.16,10.75
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56
9998,Berlin,Germany,2023-02-03,67.43,96.79,43.23,29.19,6.01,148.50,26.21,58.54,2.71
9999,Bangkok,Thailand,2023-06-13,16.34,28.80,50.48,21.20,0.49,17.41,2.50,66.05,5.01